baseURL = "https://example.com"
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
title = "Thiago Guimarães Tavares"
theme = "anatole"

enableEmoji = true
pygmentsstyle = "vs"
pygmentscodefences = true

[params]
  title = "Thiago Guimarães Tavares"
  author = "thiagogmta"
  description = "💻 | Bora #aprender sobre #tecnologia?"
  profilePicture = "images/profile.png"
  displayMode = "light"

[[params.socialIcons]]
  icon = "fab fa-linkedin"
  title = "Linkedin"
  url = "https://de.linkedin.com/"
[[params.socialIcons]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://de.linkedin.com/"
[[params.socialIcons]]
  icon = "fab fa-instagram"
  title = "Instagram"
  url = "https://de.linkedin.com/"    
[[params.socialIcons]]
  icon = "fas fa-envelope"
  title = "E-mail"
  url = "https://de.linkedin.com/" 

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Quem Sou"
  weight = 300
  identifier = "about"
  url = "posts/about/"